export const INIT_EMPLOYEES = 'INIT_EMPLOYEES';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const UPDATE_EMPLOYEE = 'UPDATE_EMPLOYEE';
export const DELITE_EMPLOYEE = 'DELITE_EMPLOYEE';
export const FILTER_EMPLOYEE = 'FILTER_EMPLOYEE';
